name: cli_hook
description: 
  A tool package for developing cli tools.
  Use cli_hook to make you cli work with hooks system.
version: 0.1.2
homepage: https://github.com/hyiso/flutterw
repository: https://github.com/hyiso/flutterw/tree/main/packages/cli_hook

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
