name: cli_wrapper
description:
  A tool package for developing flutter or dart cli.
  Use cli_wrapper to wraps a cli to support command hooks system.
version: 0.4.1
homepage: https://github.com/hyiso/flutterw
repository: https://github.com/hyiso/flutterw/tree/main/packages/cli_wrapper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
